### ISSUE TITLE
What is our total number of SORNs?

### ISSUE THREAD

**Issue by ondrae** [18F/all_sorns#10]
Right now we are at 2000. That feels very low.
The Federal Register has way more, this screenshot shows search results that should be similar to our API calls. These are before we filter out matching, rulemaking, or implementation SORNs. 
![Screen Shot 2020-10-13 at 10 45 01 AM](https://user-images.githubusercontent.com/595778/96479434-d0076900-11ed-11eb-8d15-b018b8f2418b.png)

Based on latest user research, I think we may want to include the above, but not fully parse them. Just keep the basic info from the api and show links to them if the user wants to research more.

The low numbers we have can also be from errors in our code, we don't have good error handling set up yet. I've also noticed some SORNs where the title doesn't mention 'matching' or the other unwanted types, but it'll be detailed in the `action` section.

- [ ] Talk to partners on what kinds of SORNs to include.
- [ ] Filter out the unwanted sorns based on `action` as well as the `title`. Right now we only filter out on `title`.

**Comment by ondrae** [comment]
Peter ran an update locally and has 4000 total!

**Comment by ondrae** [comment]
We got up to 5700 on production.

**Comment by ondrae** [comment]
I've done a run locally that included all the "matching", "rulemaking", and "implementation" SORNs. That count is 6466.

The only filtering done there is that the API title must include "Privacy Act of 1974"

**Comment by peterrowland** [comment]
Still open because - we want to explore the ~1,000 search results that don't have 'Privacy Act of 1974' in the API title. Maybe an agency doesn't do it?

**Comment by ondrae** [comment]
Here are all the Federal Register API responses to our query of `Privacy Act of 1974; System or Records` that don't have the term `Privacy Act of 1974` in their API title response. There are 893 results.

https://drive.google.com/file/d/1euJ4xm427-PiuWbpZQkZHbGCNJrLhEcQ/view?usp=sharing

**Comment by ondrae** [comment]
@igor had the good idea to filter on the word system. 

Exploring it some more I think we want to accept any result that has either of the terms 'Privacy Act' OR 'System(s) of Record" OR 'Computer matching' in the title. Case insensitive and search for the singular and plural of systems.

**Comment by ondrae** [comment]
I went even deeper. 

1. First we filter and keep results with the words "Privacy Act".
2. Then we filter and keep results with the word "system" case insensitive.
3. Then we filter and discard the 26 results with the word "collection"
4. Then we add in these five that I found below. We don't want to use the word amendment, cause there are 68, mostly non-sorns with that word.

Amendment for the EPA Travel, Other Accounts Payable and Accounts Receivable Files (EPA-29) | https://www.federalregister.gov/documents/2015/07/30/2015-18722/amendment-for-the-epa-travel-other-accounts-payable-and-accounts-receivable-files-epa-29
-- | --
Amendment of the External Compliance Program Discrimination Complaint Files, EPA-21 | https://www.federalregister.gov/documents/2014/10/24/2014-25417/amendment-of-the-external-compliance-program-discrimination-complaint-files-epa-21


Amendment of PeoplePlus (EPA-1) | https://www.federalregister.gov/documents/2014/06/05/2014-13058/amendment-of-peopleplus-epa-1
-- | --



Type of Action: Amendment | https://www.federalregister.gov/documents/2009/08/21/E9-20209/type-of-action-amendment
-- | --



Amendment to General Routine Uses | https://www.federalregister.gov/documents/2008/01/14/E8-445/amendment-to-general-routine-uses
-- | --

**Comment by ondrae** [comment]
[No title available] | https://www.federalregister.gov/documents/2007/05/29/07-2638/no-title-available
-- | --
[No title available] | https://www.federalregister.gov/documents/2004/03/15/04-5676/no-title-available
