### ISSUE TITLE
Browse Mode

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/all_sorns#114]
An alternative navigation model that allows privacy officers to look through SORNs without a keyword search
- [ ] Visual Design
- [ ] Implementation

consider using a different route for landing page, results, browse mode. Right now, in order to get to filters / section, must have a search term in the url.

**Comment by igorkorenfeld** [comment]
Based on Laura's suggestion I've added a design with a "Browse All SORNs" button (in a secondary button style). 

![1LandC](https://user-images.githubusercontent.com/52677065/103947741-96683f00-5106-11eb-9b41-de5a10956109.png)

[Clickable prototype](https://www.figma.com/proto/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=685%3A0&viewport=-5378%2C-4833%2C0.6012895703315735&scaling=min-zoom). This is just to show the flow and interaction, so the design of the filters might be a little different, and there are only 3 cards displayed.

One issue with this design is that after entering a search term, if a privacy officer wants to get back to browse mode, there isn't necessarily a clear way to do that, beyond reloading the home page. I am not sure if this would be a common use case or not, and if reloading the page would be a problem, so would welcome any thoughts about thatIn which case an alternative design is to have the button be a persistent text button under the search bar:

![1Land](https://user-images.githubusercontent.com/52677065/103947761-a08a3d80-5106-11eb-81d5-f56b4d015fef.png)

A possible disadvantage, or something to watch for with this design is that it's a little less noticeable than the outlined button. This would be something to keep in mind for testing.

**Comment by ondrae** [comment]
I like it Igor. I like the link more than the button.

I was messing around and doing something similar. A way to get to browse mode, then optionally turn on the advanced search options.

<img width="1013" alt="Screen Shot 2021-01-07 at 2 29 19 PM" src="https://user-images.githubusercontent.com/595778/103952405-3917c200-50f5-11eb-9eea-45044799a510.png">
<img width="1076" alt="Screen Shot 2021-01-07 at 2 29 35 PM" src="https://user-images.githubusercontent.com/595778/103952418-3f0da300-50f5-11eb-98b4-f4a5ec925a66.png">
<img width="1048" alt="Screen Shot 2021-01-07 at 2 29 46 PM" src="https://user-images.githubusercontent.com/595778/103952442-459c1a80-50f5-11eb-9028-ab11e4eacdc9.png">

**Comment by igorkorenfeld** [comment]
Awesome, thank you!

Can you say more about hiding the search filters? I am curious about the advantage that would have over the filter options being present but collapsed

**Comment by ondrae** [comment]
Closed by #174, doing an empty search lets you browse all the SORNs.
