### ISSUE TITLE
Simplify process for applying filters

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/all_sorns#169]
We have seen in testing that users are not sure how to apply the filters once they've selected them. Additionally the page "jumps" when a filter get selected because an Active filter tag gets added to the page which pushes the list of cards/records down. 

There are two ideas in an attempt to make this interaction clearer: 

### Option 1
Have the filters apply instantly when a user checks a filter box.  

The advantage of this is that it puts less burden on the user. The change to the page is tied directly to their action, create a clear cause-and-effect interaction

The disadvantage is that the page will have to refresh every time the user adds a new filter. This can slow. Additionally if a user wants to apply multiple filters, once the page loads they will have to navigate and expand the filter section again, which might feel repetitive and frustrating.  

### Option 2
Add an "Apply filters" button that the user will need to click on in order to apply the filters.

The advantage here is that only one refresh and selection is required to apply multiple filters

A disadvantage is that there is still a two-step process to applying the filters and there is a chance a user will not see the "Apply filters" button. Additionally this doesn't solve the  jump on filter selection issue caused by the tag. 

A possible fix for the page jump issue is limiting the height of the filter list boxes so that a user scrolls within that area rather than on the whole page. That way they can see that the jump is caused by the addition of the tags.  

***

These are interaction advantages and disadvantages, so they don't consider the engineering costs and difficulty levels. 

Todo
- [x] Discuss and choose an option
- [ ] If Option 2 decide on a design
- [ ] Implement

**Comment by igorkorenfeld** [comment]
From our Slack conversation it sounds like we are going to go with option 2. 

Three different design options (names are based on my artboards). In all of these I think we ought to limit the height of the a list within each section so the tags remain visible. "Active filters" is perhaps misleading as well. Maybe it ought to be "Selected filters"? 

### A  
Small button above the filters 

![PrvOps_ApplyFilter_A](https://user-images.githubusercontent.com/52677065/107582514-99ec5b80-6bc7-11eb-833b-ea21c2af928e.png)

### K 
Give the filters section a subtle background to group them all more, and add a primary style button.

![PrvOps_ApplyFilter_K](https://user-images.githubusercontent.com/52677065/107582522-9b1d8880-6bc7-11eb-8f27-0f87db0e9ad8.png)

### J
Place an apply button inside each accordion 
![PrvOps_ApplyFilter_J](https://user-images.githubusercontent.com/52677065/107582518-9a84f200-6bc7-11eb-8795-829d19498ae0.png)

**Comment by ondrae** [comment]
Closed by #172
