### ISSUE TITLE
Agency filtering broken

### ISSUE THREAD

**Issue by ondrae** [18F/all_sorns#195]
### What is broken?
![Screen Shot 2021-04-21 at 12 12 37 PM](https://user-images.githubusercontent.com/595778/115608278-ebd1f180-a29a-11eb-9015-1c5197a1ffc7.png)

![Screen Shot 2021-04-21 at 12 13 48 PM](https://user-images.githubusercontent.com/595778/115608402-0efca100-a29b-11eb-8a93-070fa67d5acc.png)

It appears a duplicate agency got into the list. The very well known Federal government agency called Saint Lawrence Seaway Development Corporation.

![Screen Shot 2021-04-21 at 12 14 32 PM](https://user-images.githubusercontent.com/595778/115608525-3bb0b880-a29b-11eb-887b-80b496bb5105.png)

That is probably causing the error, but the error logging doesn't seem totally related.

### First guess at fixing
- Delete the duplicate agency
- Investigate why a dupe was created

**Comment by hartsick** [comment]
I'm having some trouble reproducing this. Here is the behavior I'm currently seeing locally and in both [hosted](https://all-sorns.app.cloud.gov/) [environments](https://all_sorns.app.cloud.gov/):
* Search 'land', see results: local (202), all-sorns (206), all_sorns (196)
* On lefthand side under 'agencies', search 'usda' and click the box for 'Department of Agriculture'.
* See results seem to be filtered: local (21), all-sorns (22), all_sorns (20)

Without looking into more I'm not sure why these numbers are different, but filtering seems to work as I'd expect.

**Comment by hartsick** [comment]
Ooh, got it! Here are steps to reproduce:
* Search 'elections', see results: local (287), all-sorns (293), all_sorns (284)
* On lefthand side under 'agencies', search 'eac' and click the box for 'Election Assistance Commission'
* See results not filter. This message in console after filtering:
<img width="1078" alt="Screen Shot 2021-10-29 at 3 05 44 PM" src="https://user-images.githubusercontent.com/3675092/139506532-2cc198a2-63db-4a10-93bd-a1749ce13ea2.png">
