### ISSUE TITLE
Where to put pagination menu? attn: igor

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/all_sorns#58]

**Comment by igorkorenfeld** [comment]
A pattern I've seen that I think makes sense for these longer scrolls is to repeat it at the top and bottom, I think that's what we should go for

### Top 
![image](https://user-images.githubusercontent.com/52677065/99702954-7ef4ca00-2a64-11eb-9ddd-34fc7487c493.png)

### Bottom 
![image](https://user-images.githubusercontent.com/52677065/99702992-8e741300-2a64-11eb-9580-651797342772.png)

**Comment by ondrae** [comment]
Can you make a figma for the pagination? So I can get the right icon, spacing, font, etc.

**Comment by igorkorenfeld** [comment]
Sure thing, [it's on this page](https://www.figma.com/file/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=76%3A1)

Just to be clear, the pagination should be right aligned with the cards,  and there should 2 units of spacing between page numbers

**Comment by ondrae** [comment]
Here is 8px padding
<img width="312" alt="Screen Shot 2020-11-20 at 11 56 17 AM" src="https://user-images.githubusercontent.com/595778/99844126-7dd8a100-2b27-11eb-87bc-3e01a87b5dcd.png">

Here is 16px padding.
<img width="357" alt="Screen Shot 2020-11-20 at 11 56 02 AM" src="https://user-images.githubusercontent.com/595778/99844175-8d57ea00-2b27-11eb-908f-80bee82f10ec.png">

**Comment by igorkorenfeld** [comment]
Interesting, I wonder why the spacing is different from Figma's measures. But let's go with 8px. We'll also need to further distinguish between the active page and the other pages. I'll work on that, but I think we should be able to draw from what we did on the GSA tool
