### ISSUE TITLE
Validating Data Quality of govinfo PAIs

### ISSUE THREAD

**Issue by peterrowland** [18F/all_sorns#6]
- [ ] Set up conversation with GPO.

The GPO publishes [Privacy Act Issuances](https://www.govinfo.gov/help#about_privacy_act_issuances.htm). They are packaged as one big XML file containing all agency SORNs to date, and in a structured format. This would be useful, but is the data reliable?

Questions to answer:

Are the initial publication dates accurate (in the `<previouslyPublished>` section)?

- Appears so. They are correct for all of GSAs SORNs published since 2015.

Do the SORNs change at all from bundle to bundle to reflect modifications?

- Appears so. For example GSA childcare-1. Modified in 2008 to add breach routine use (h.). In 2007 compilation, childcare-1 has a - g, in 2019 compilation, it has a - h.
- Validate with other modified SORNs

Does the most current bundled version match the most current version in the federal register?

Do the bundled versions contain SORNs that have been rescinded?

- No. For example GSA's GOVT-5 was rescinded in 2016 but still appears in 2019 compilation.

**Comment by ondrae** [comment]
We[ talked with the GPO](https://docs.google.com/document/d/1SKm0dMEHLYRPBAb86H2SPpjBf3OFSwsR3A3-z3Oy36U/edit#heading=h.hb04iw5dgzq3) and they gave us some clues to investigate to see if we can get the full SORN from piecing together different data.

We can get complete SORNs from the Federal Register, but we have to do parsing on our own.

The GPO does their own parsing and transformations, which is much easier to work with, but we've only found half of the SORN in their data. The beginning preamble isn't included. Can we find it all elsewhere? Their mods file may have it?


Explore these to see if we can get all the sections.
https://www.govinfo.gov/app/details/FR-2015-06-04/2015-13701
https://www.govinfo.gov/app/collection/pai
https://www.govinfo.gov/metadata/granule/FR-2015-06-04/2015-13701/mods.xml
https://www.federalregister.gov/api/v1/documents/2015-13701?publication_date=2015-06-04
https://api.govinfo.gov/docs
https://api.govinfo.gov/collections/PAI/2020-09-01T00:00:00Z?offset=0&pageSize=100?api_key=DEMO_KEY
https://api.govinfo.gov/collections/PAI/2020-09-01T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY
