### ISSUE TITLE
Add explanation on the search page

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/all_sorns#60]
Add explanation on the search interface that search by number is just for a-108 compliant SORNs - and link back to about page for explanation.

**Comment by igorkorenfeld** [comment]
Layout idea for the explanation

Text: 
"This dashboard enables targeted search of System of Records Notices (SORN). The dashboard regularly pulls newly published SORNs from the Federal Register, and includes document from 1994 to the present day. **Learn more about this tool**" 

The last sentence would link to the about page


![image](https://user-images.githubusercontent.com/52677065/99732273-37ceff00-2a8d-11eb-8e06-99334763d0f2.png)

**Comment by igorkorenfeld** [comment]
Perhaps the text should also include some reference to CMAs?

**Comment by ondrae** [comment]
This is what I have so far.

![Screen Shot 2020-11-30 at 3 02 56 PM](https://user-images.githubusercontent.com/595778/100676155-2bfcfb80-331d-11eb-8937-c396c32abe35.png)

**Comment by igorkorenfeld** [comment]
Nice! I think this works well for now, and we can add more styling to it when we style the rest of the site. So for now the size and color I work. 

Couple of items to change.
1. The measure (text-width) is a little longer than I hoped, so I made an in-line comment to change it from 10 columns to 9
2. Could we add a class to the intro text and give it a `line-height: 1.5`? The text is a bit scrunched, and especially when you have longer measures you want to have some more leading. 
3. When I first open the site locally the USA banner is expanded. If I refresh the page it collapses. I think Laura mentioned this might be due to our asset pipeline? Maybe needs to be a separate issue, but wanted to flag (no pun intended)
