### ISSUE TITLE
UI for multiple agency search?

### ISSUE THREAD

**Issue by ondrae** [18F/all_sorns#65]
@igorkorenfeld I see this in Figma.
<img width="275" alt="Screen Shot 2020-11-25 at 4 09 35 PM" src="https://user-images.githubusercontent.com/595778/100293536-e7e2b300-2f38-11eb-9633-bb43b4997daa.png">

It looks like a combo-box meets a multi-selct meets a checkbox list.

USWDS doesn't have anything like that.

I do see a discussion where the USWDS team didn't get to any answers on it. https://github.com/uswds/uswds/issues/22

I can hack something together, but I can't say it will be elegant or meet accessibility requirements.

To get some ideas of what is possible, ignoring accessibility needs, see https://harvesthq.github.io/chosen/

**Comment by igorkorenfeld** [comment]
I did some more digging and it look like https://select2.org/ is more actively maintained and has addressed some a11y issues based on [this conversation](https://github.com/select2/select2/issues/3744)

Might be a stretch, but maybe @adunkman knows more about that chosen library?

The main goal with this is to make it easier to find the agencies that a privacy officer is interested in searching, but I definitely wouldn't want to ignore a11y issues. The dropdown portion of the combobox is not really necessary, I mostly want to filter the agency names to that ones that the user types.

**Comment by adunkman** [comment]
I used to maintain Chosen — I can say that it’s unlikely to receive much attention (no shade; it’s not an organizational priority). Last time I had to implement something like this, I used https://github.com/alphagov/accessible-autocomplete, but it looks like it needs a new maintainer.

**Comment by ondrae** [comment]
Closed by #140
