### ISSUE TITLE
Search by publication date

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/all_sorns#74]
- [X] Design
- [ ] Implement

**Comment by igorkorenfeld** [comment]
New language for text label:
[Figma artboard](https://www.figma.com/file/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=436%3A45)


![PubDate](https://user-images.githubusercontent.com/52677065/101800017-a2d68900-3ac1-11eb-86d1-542e66184d89.png)

**Comment by ondrae** [comment]
<img width="324" alt="Screen Shot 2020-12-16 at 10 22 06 AM" src="https://user-images.githubusercontent.com/595778/102389956-b2a21180-3f88-11eb-9ce8-2d9a47c5d541.png">

The calendar widget thing is too squished in the sidebar.

**Comment by ondrae** [comment]
The USWDS says to use this instead. https://designsystem.digital.gov/components/form-controls/#date-input
> When the day of the week is irrelevant. If there's no benefit to knowing the day of the week for a particular date, consider date input fields.

**Comment by igorkorenfeld** [comment]
Yeah, I saw that but I guess I am not clear on how that's better than letting users pick a day rather than type it? It seems like the three boxes requires a specific date still?

**Comment by igorkorenfeld** [comment]
Updated [figma link](https://www.figma.com/file/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=516%3A268) with the date-input instead

**Comment by ondrae** [comment]
The date range picker is nicer because you can use your mouse, and you always end up with a full date.

The date input requires six different clicks or tab presses, and we have to build our own support or validation for partial dates.

**Comment by ondrae** [comment]
We could also just do year. is that precise enough?
![Uploading Screen Shot 2020-12-17 at 4.18.55 PM.png…]()

**Comment by igorkorenfeld** [comment]
Yeah, I like that idea, I think it's a good starting place.
