### ISSUE TITLE
[Bug] Resolve "Found In" Blanks

### ISSUE THREAD

**Issue by igorkorenfeld** [18F/all_sorns#82]
The "Found In" section is coming up blank in search results

![image](https://user-images.githubusercontent.com/52677065/102380879-55549300-3f7d-11eb-9cd0-d65b3b14f8ed.png)

To replicate:
- Open the tool and type in "Financial Audit" in the search box

AC
- [ ] Any result displayed has a Found In section with at least one match highlighted
- [ ] Added a test to detect this issue in the future

**Comment by ondrae** [comment]
Just like we suspected. 

Any two word searches are kind of broken. The postgres full test search is returning ranked matches. It returns a match anytime it finds the separate words anywhere in the content, just ranked lower if they aren't consecutive words.

Then our snippet code was looking for exact matches.

**Comment by ondrae** [comment]
One solution is two use what postgres gives us, and just highlight everything.
<img width="655" alt="Screen Shot 2020-12-18 at 5 19 22 PM" src="https://user-images.githubusercontent.com/595778/102677096-a15a3000-4155-11eb-9480-a51d8b556cc8.png">

I do not know how you would snippet something like that.

**Comment by ondrae** [comment]
Another option is do take postgres results, then do our own filtering on them to keep only exact matches. It make searching slower and it doesn't play nice with our pagination (weirdly).

**Comment by igorkorenfeld** [comment]
It seems like the exact match might be the right way to go for the time we have left. It seems in-tune with how users expected search to behave in our testing with static prototypes, and maybe we can update the helper text to say it. Something along the terms of "Search for SORNs by entering a keyword (find exact matches)" or "Search for SORNs by entering a keyword (will return exact matches)"? @peterrowland any thoughts on that text?
