### ISSUE TITLE
System Numbers - Parsing and Appearance

### ISSUE THREAD

**Issue by peterrowland** [18F/all_sorns#87]
look for system numbers in summary section if not found in system name to reduce number of unknowns.

Should we change the way we present unavailable SORNs?

**Comment by peterrowland** [comment]
I propose swapping the location of agency and system number:

- Put agency at the top as just the name of the agency
- Put system number in the citation field.
- Then, either hide the system number when there isn't one, or insert text 'System Number Unavailable (here's why: link to section of the 'About' page describing what gets parsed)

<img width="512" alt="Screen Shot 2020-12-21 at 11 38 18 AM" src="https://user-images.githubusercontent.com/1530932/102815645-8966f400-4381-11eb-8e17-30e8a77b087c.png">

**Comment by ondrae** [comment]
We could also just drop the system number. If we aren't able to get it in a way that isn't confusing, then drop it. A108 says its supposed to be "System Name and Number" anyways.

**Comment by igorkorenfeld** [comment]
Mockups of these alternatives: 
With agency name at the top (2 examples): 

![Record_1AgencyName](https://user-images.githubusercontent.com/52677065/102935293-b935fa80-445a-11eb-8bde-f0b91771ecbb.png)

![Record_1AgencyName-2](https://user-images.githubusercontent.com/52677065/102935668-71fc3980-445b-11eb-9047-0aee1c4e79ed.png)
----------------------------------------------------------------------------------------------------

Title Only (2 examples):
 
![Record_2TitleOnly](https://user-images.githubusercontent.com/52677065/102935299-ba672780-445a-11eb-8c23-01530e97fc47.png)

![Record_2TitleOnly-2](https://user-images.githubusercontent.com/52677065/102935749-9bb56080-445b-11eb-959e-198ebeb932af.png)

**Comment by peterrowland** [comment]
I like the way it looks at the top - though I see how it could get a little messy if the list of agencies is long. 

Another idea - if we get the short_names from Federal Register, we could keep the agency full name where it is and put the acronym up top. That would keep the citation section complete, and allow users to quickly see which agency's SORN it is.

**Comment by igorkorenfeld** [comment]
I like that idea!

**Comment by peterrowland** [comment]
Closing this issue now that we've decided:
- We aren't going to parse system numbers now. We will leave the work that Laura has already done in the code, document, and include in the roadmap.
- We will put the agency acronym at the top of the card where we currently have the system number.
