### ISSUE TITLE
Design for Multi-agency search

### ISSUE THREAD

**Issue by peterrowland** [18F/all_sorns#89]
- add system spec for any js used.

**Comment by peterrowland** [comment]
Igor and I discussed and decided on doing the following about the agency / sections filter:

- [ ] By default nothing is checked - and no filters are applied.
- [ ] Add a section beneath active search filters section for active agency filters.
- [ ] Replace Select/Deselect all search sections with 'clear all' to disable all filters. Users will have to manually add every filter they want, but that will make it more difficult for them to attempt searches that will take a long time or clutter the active filter section.
- [ ] make agency filter checklist fixed height and scroll-able, like the section filters.
- [ ] optional: Test more compact listing format for active filters section
- [ ] optional: search bar within agency filters (what AH already mocked up is fine)

**Questions:**

- If filtering requires all filter checkboxes to be visible - can we use the active filters section instead?
- Agency acronyms: They are available as 'short_name' in the FR API. Do we have them / can we add them to our model? We could use them as a way to make the list of active agency filters more compact and maybe provide an alternate way to search for agencies.

**Comment by igorkorenfeld** [comment]
Agency active filter tags:

[Option A: ](https://www.figma.com/file/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=560%3A18194)With full agency names, always displayed

[Option B:](https://www.figma.com/file/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=560%3A18854) With full agency names, hide overflow after the second row and add a "see all" button

[Option C:](https://www.figma.com/file/q9E2ILYDXraXIkmF2i8lSV/PrvOps-Phase-4?node-id=560%3A19710) with agency short names

**Comment by ondrae** [comment]
@peterrowland These agencies don't have short_names in the api.
> ["Assassination Records Review Board", "Bureau Of The Fiscal Service", "Customs Service", "Institute Of Museum And Library Services", "National Endowment For The Humanities"]
